### ISSUE TITLE
为什么速度会这么慢？怎么才能加快了？

### ISSUE THREAD

**Issue by zuowanbushiwo** [leohuang2013/pyannote-audio_speaker-diarization_cpp#2]
你好 
     对这个项目非常感兴趣，但是看你的readme 说 耗时比较长，这是为什么？是声纹提取时间长吗？谢谢！

**Comment by leohuang2013** [comment]
主要是在STFT部分，对于这里提供的wav测试文件，其他几个stage耗时是毫秒或者秒级别，而stft则是356秒。而pyannote-audio的python部分跑stft也是秒级别，所以可以考虑转换pyannote-audio中使用stft的代码，另外一种就是自己写stft(可以参看https://github.com/kooBH/STFT）。

除此之外，还有整个代码都没有怎么优化，尤其是tensor操作部分，现在我都是自己用c++实现的，可以考虑xtensor库来替代。不过替代之前和之后也需要比较性能变化。

**Comment by zuowanbushiwo** [comment]
这个不是时域的吗？我看代码没看到有用到stft啊？ 总共就是三个过程：segment 使用的PyanNet 这个是时域的？接着 embing  使用的是wespeaker 的方案，可以直接使用 `https://github.com/wenet-e2e/wespeaker/tree/master/runtime/onnxruntime` 这个项目 这里面可能需要stft，提取fbank，但是看它 reamde 是很快的，最后是聚类 也不需要stft？

**Comment by Leeviber** [comment]
> 这个不是时域的吗？我看代码没看到有用到stft啊？ 总共就是三个过程：segment 使用的PyanNet 这个是时域的？接着 embing 使用的是wespeaker 的方案，可以直接使用 `https://github.com/wenet-e2e/wespeaker/tree/master/runtime/onnxruntime` 这个项目 这里面可能需要stft，提取fbank，但是看它 reamde 是很快的，最后是聚类 也不需要stft？

EmbeddingModel需要的输入是STFT。这里使用的是v2.1的基于speechbrain的[embedding](https://github.com/pyannote/pyannote-audio/blob/0b45103cb228a81a9d9d776cca92694cb30ddb41/pyannote/audio/pipelines/speaker_verification.py#L209C2-L209C2)
 v3.0 embedding换成了 [WeSpeaker](https://github.com/wenet-e2e/wespeaker)

**Comment by zuowanbushiwo** [comment]
好的，感谢了解了！
